### ISSUE TITLE
failed to find markiewb.mavenproject14.Bundle

### ISSUE THREAD

**Issue by markiewb** [Chris2011/nb-debugger-utils#2]
```
#149833: failed to find markiewb.mavenproject14.Bundle in locale en_US in ModuleCL@17a9fb56[de.markiewb.netbeans.plugins.debuggerutils] for C:\Users\markiewb\AppData\Roaming\NetBeans\8.1.flexkosten\modules\de-markiewb-netbeans-plugins-debuggerutils.jar; resource lookup of markiewb/mavenproject14/Bundle.properties -> null
Caused: java.util.MissingResourceException: No such bundle markiewb.mavenproject14.Bundle
    at org.openide.util.NbBundle.getBundle(NbBundle.java:451)
[catch] at org.netbeans.StandardModule.getLocalizedAttribute(StandardModule.java:169)
    at org.netbeans.modules.autoupdate.services.ModuleUpdateElementImpl.getRawCategory(ModuleUpdateElementImpl.java:182)
    at org.netbeans.modules.autoupdate.services.ModuleUpdateElementImpl.getCategory(ModuleUpdateElementImpl.java:194)
    at org.netbeans.api.autoupdate.UpdateElement.getCategory(UpdateElement.java:198)
    at org.netbeans.modules.autoupdate.ui.Utilities.makeInstalledCategories(Utilities.java:109)
    at org.netbeans.modules.autoupdate.ui.InstalledTableModel.setUnits(InstalledTableModel.java:87)
    at org.netbeans.modules.autoupdate.ui.InstalledTableModel.setUnits(InstalledTableModel.java:92)
    at org.netbeans.modules.autoupdate.ui.PluginManagerUI.refreshUnitsInBackground(PluginManagerUI.java:608)
    at org.netbeans.modules.autoupdate.ui.PluginManagerUI.initialize(PluginManagerUI.java:251)
    at org.netbeans.modules.autoupdate.ui.PluginManagerUI.access$100(PluginManagerUI.java:79)
    at org.netbeans.modules.autoupdate.ui.PluginManagerUI$1.run(PluginManagerUI.java:134)
    at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
    at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
    at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
    at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

**Comment by markieww** [comment]
Still valid in 1.0.0

```
Caused: java.util.MissingResourceException: No such bundle markiewb.mavenproject14.Bundle
    at org.openide.util.NbBundle.getBundle(NbBundle.java:451)
```
